Crescendo
green-goo-dao/flow-utils pull request #30
Opened 2024-01-12 03:10 UTC by austinkline

2024-03-14 13:56 UTC, bjartek requested changes
Left some questions and suggestions, very well done!

2024-03-14 13:56 UTC, bjartek commented on contracts/AddressUtils.cdc
> +            "CRESCENDO" : 0x6834ba37b3980209,
```suggestion
            "PREVIEWNET" : 0x5211829E88528817,
,
```

2024-03-14 13:56 UTC, bjartek commented on contracts/AddressUtils.cdc
>          for network in ["MAINNET", "TESTNET", "EMULATOR"] {
```suggestion
        for network in ["MAINNET", "TESTNET", "EMULATOR", "PREVIEWNET"] {
```

2024-03-14 13:56 UTC, bjartek commented on contracts/ScopedFTProviders.cdc
> +        access(self) let provider: Capability<auth(FungibleToken.Withdraw) &{FungibleToken.Provider}>
this is interesting to me, how would the migration migrate an existing scoped provider? 
Would `Cap<&{FT.Provider}>` be done as `Cap<auth(FT.Withdraw) &{FT.Collection}>` or as `auth(FT.Withdraw) &{FT.Provider}`?

2024-03-14 13:56 UTC, bjartek commented on contracts/ScopedNFTProviders.cdc
> +    access(all) resource ScopedNFTProvider: NonFungibleToken.Provider {
This is interesting to me, will a `Cap<&ScopedNFTProvider}` be able to be stored as a `Cap<auth(FT.Withdraw) &{NonFungibleToken.Provider}` because previously you could store it as something that implemented the interface? Should the access(all) here really be `access(FT.Withdraw)`?

2024-03-14 13:56 UTC, bjartek commented on contracts/ScopedNFTProviders.cdc
> +            let nft = self.provider.borrow()!.borrowNFT(id)
```suggestion
            let nft = self.provider.borrow()?.borrowNFT(id)
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
> +        "mainnet": "0xf233dcee88fe0abe"
```suggestion
        "mainnet": "0xf233dcee88fe0abe",
        "previewnet" :"0xa0225e7000ac82a9"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
> +        "mainnet": "0x1654653399040a61"
```suggestion
        "mainnet": "0x1654653399040a61",
        "previewnet": "0x4445e7ad11568276"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
> +        "mainnet": "0x1d7e57aa55817448"
```suggestion
        "mainnet": "0x1d7e57aa55817448",
        "previewnet": "0xb6763b4399a888c8"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
>          "mainnet": "0xf233dcee88fe0abe"
```suggestion
        "mainnet": "0xf233dcee88fe0abe",
        "previewnet": "0xa0225e7000ac82a9"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
>          "mainnet": "0x1d7e57aa55817448"
```suggestion
        "mainnet": "0x1d7e57aa55817448",
        "previewnet": "0xb6763b4399a888c8"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
>          "mainnet": "0x1d7e57aa55817448"
```suggestion
        "mainnet": "0x1d7e57aa55817448",
        "previewnet" : "0xb6763b4399a888c8"
```

2024-03-14 13:56 UTC, bjartek commented on flow.json
> +        "mainnet": "0x1d7e57aa55817448"
```suggestion
        "mainnet": "0x1d7e57aa55817448",
        "previewnet":"0xb6763b4399a888c8"
```

2024-03-14 13:58 UTC, bjartek commented on contracts/ScopedNFTProviders.cdc
> +    access(all) resource ScopedNFTProvider: NonFungibleToken.Provider {
i think i am just overthinking things here but this is something that would have been nice to be 100% sure about.

2024-03-14 14:27 UTC, austinkline commented on contracts/ScopedNFTProviders.cdc
> +    access(all) resource ScopedNFTProvider: NonFungibleToken.Provider {
I'll send this PR to the cadence team for feedback from them on the migration piece specifically, doesn't hurt to be extra sure

2024-03-27 23:42 UTC, austinkline commented on contracts/ScopedNFTProviders.cdc
> +    access(all) resource ScopedNFTProvider: NonFungibleToken.Provider {
Forgot to update here, the feedback we got was that what we're doing here looks good. We should probably check that migrations work as expected either way, but I think that suffices for now

2024-03-27 23:48 UTC, austinkline commented on contracts/ScopedFTProviders.cdc
> +        access(self) let provider: Capability<auth(FungibleToken.Withdraw) &{FungibleToken.Provider}>
My understanding is that the interface types will be migrated as-is. And the entitlements will be added with them. So in that case, it is 

```
auth(FT.Withdraw) &{FT.Provider}
```

2024-05-28 16:09 UTC, merged